### ISSUE TITLE
正在获取应用信息...然后就没有反应了

### ISSUE THREAD

**Issue by sunzongzheng** [WrBug/DeveloperHelper#24]
用的太极，在太极里勾上了模块，切到其他应用，点击获取应用信息都会没有反应，只有在`易开发`上点击悬浮穿才会出现应用信息

**Comment by Easy-Ez** [comment]
解决了吗 老哥~

**Comment by sunzongzheng** [comment]
@sh1tge 进群看了公告，给一个`允许显示在其他应用上`的权限就可以了

**Comment by Easy-Ez** [comment]
@sunzongzheng  ok 谢谢~
小米Android9 上勾选 “后台弹出界面”
